Update Jenkinsfile

diff --git a/11.css-escape-loading-animation/Jenkinsfile b/11.css-escape-loading-animation/Jenkinsfile
--- a/11.css-escape-loading-animation/Jenkinsfile
+++ b/11.css-escape-loading-animation/Jenkinsfile
@@ -7,7 +7,6 @@ pipeline {
 
         SERVER_IP    = "172.31.29.127"
         SSH_USER     = "ubuntu"
-        CREDENTIALS  = "server"
     }
 
     stages {
@@ -22,7 +21,7 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 sh '''
-                docker build -t $DOCKER_IMAGE:$DOCKER_TAG "./11.css-escape-loading-animation"
+                docker build -t $DOCKER_IMAGE:$DOCKER_TAG ./11.css-escape-loading-animation
                 '''
             }
         }
@@ -43,16 +42,27 @@ pipeline {
         }
 
         stage('Deploy to EC2') {
-    steps {
-        sshagent(['server']) {
-            sh '''
-            ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "
-                docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
-                docker stop app || true &&
-                docker rm app || true &&
-                docker run -d -p 80:80 --name app $DOCKER_IMAGE:$DOCKER_TAG
-            "
-            '''
+            steps {
+                sshagent(['server']) {
+                    sh '''
+                    ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "
+                        docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
+                        docker stop app || true &&
+                        docker rm app || true &&
+                        docker run -d -p 80:80 --name app $DOCKER_IMAGE:$DOCKER_TAG
+                    "
+                    '''
+                }
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Deployment Successful"
+        }
+        failure {
+            echo "Deployment Failed"
         }
     }
 }
